name: Build Windows EXE

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  workflow_dispatch:

env:
  # Update these to match your project
  ENTRY_PATH: src/main.py    # e.g., main.py or src/app.py
  APP_NAME: DOOM-Tools       # The name of your executable
  PYTHON_VERSION: "3.12.3"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyinstaller

      # If you need to include data files, icons, or resources, you can either:
      # - Add --add-data arguments below (Windows format "source;dest")
      # - Or check in a PyInstaller .spec file and use: pyinstaller your.spec
      - name: Build exe with PyInstaller
        shell: bash
        run: |
          echo "Building $APP_NAME from $ENTRY_PATH"
          pyinstaller --onefile --name "$APP_NAME" "$ENTRY_PATH"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows
          path: dist/${{ env.APP_NAME }}.exe

  # Optional: publish a release when you push a tag, attaching the built exe
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/${{ env.APP_NAME }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}